# Terraform Backend Configuration
#
# This configures Terraform to store state in Google Cloud Storage.
# The state file is versioned and encrypted at rest.
#
# Generated by: scripts/bootstrap.sh
# Bucket: gs://k8satlas-tfstate

terraform {
  backend "gcs" {
    bucket = "k8satlas-tfstate"
    prefix = "terraform/state/prod"
  }
}
